# This is a basic workflow to help you get started with Actions

name: Upload changes to Azure Storage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, rs/new-pipeline ]
env:
  STORAGEACCOUNTNAME: catalogoutputdev
  TEMPLATECONTAINER: templates
  WEBCONTAINER: $web

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZUREDEPLOYKEY}}

      # Runs a single command using the runners shell
      - name: Install depencies
        run: sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install ruby ruby-dev build-essential zlib1g-dev && sudo gem install bundler
      - name: Run build.sh
        run: chmod u+x ./build.sh && ./build.sh
      - name: Upload template
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload-batch --account-name ${{env.STORAGEACCOUNTNAME}} --auth-mode key -d ${{env.TEMPLATECONTAINER}} -s "./_site/templates/*.html"
      - name: Upload resources
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az storage blob upload-batch --account-name ${{env.STORAGEACCOUNTNAME}} --auth-mode key -d ${{env.WEBCONTAINER}} -s "./_site/css"
            az storage blob upload-batch --account-name ${{env.STORAGEACCOUNTNAME}} --auth-mode key -d ${{env.WEBCONTAINER}} -s "./_site/fonts"
            az storage blob upload-batch --account-name ${{env.STORAGEACCOUNTNAME}} --auth-mode key -d ${{env.WEBCONTAINER}} -s "./_site/js"
            az storage blob upload-batch --account-name ${{env.STORAGEACCOUNTNAME}} --auth-mode key -d ${{env.WEBCONTAINER}} -s "./_site/index.html"
